name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  continuous-integration:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          scheme: ${{ 'Radar STATS' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          export device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild test -scheme "$scheme" CODE_SIGN_IDENTITY="-" -destination "platform=$platform,name=$device"
      - name: Deploy
        uses: devmasx/merge-branch@v1.3.0
        with:
          target_branch: master
